export const ROUTES = Object.freeze({
  indie: {
    id: "indie",
    label: "个人势",
    statement: "保留完整内容与资产自主权，自行承担经营成本。",
    launchImpressions: 3000,
    weeklyToolCost: 3000n,
    creatorShareBps: 10000,
    agencyId: null,
    assetOwner: "PLAYER",
    strengths: ["内容自主", "资产自主", "自由外包"],
  },
  homolive: {
    id: "homolive",
    label: "Homolive",
    statement: "获得舞台与视觉企划入口，同时承担资源申请和项目协同。",
    launchImpressions: 30000,
    weeklyToolCost: 0n,
    creatorShareBps: 6000,
    agencyId: "agency_homolive",
    assetOwner: "AGENCY",
    strengths: ["舞台企划", "视觉项目", "组织曝光"],
  },
  niji2434: {
    id: "niji2434",
    label: "2434",
    statement: "获得多人企划与联动网络入口，需要主动经营合作和辨识度。",
    launchImpressions: 30000,
    weeklyToolCost: 0n,
    creatorShareBps: 6000,
    agencyId: "agency_2434",
    assetOwner: "AGENCY",
    strengths: ["多人企划", "合作网络", "特色节目"],
  },
});

export const AGENCIES = Object.freeze({
  agency_homolive: {
    id: "agency_homolive",
    routeId: "homolive",
    label: "Homolive",
    sourceType: "DESIGN_VALUE",
    auditionTemplate: {
      id: "audition_homolive_standard",
      name: "舞台与综合创作招募",
      minimumPrimaryLanguage: 50,
      minimumAvailableWeeklySlots: 4,
      minimumValidWorks: 1,
      relatedSkills: ["performance", "production", "planning"],
      targetDirections: ["music", "creative"],
      supportedLanguages: ["jp", "en"],
      requiredWorkTypes: ["PUBLIC_CONTENT", "MUSIC", "STAGE"],
    },
    weeklyResourceCapacity: { MANAGER_ASSIST: 16, RECORDING_SLOT: 4, THREE_D_SLOT: 3, PROJECT_COORDINATION: 4, PROMOTION_SLOT: 2 },
  },
  agency_2434: {
    id: "agency_2434",
    routeId: "niji2434",
    label: "2434",
    sourceType: "DESIGN_VALUE",
    auditionTemplate: {
      id: "audition_2434_standard",
      name: "多人企划与特色节目招募",
      minimumPrimaryLanguage: 50,
      minimumAvailableWeeklySlots: 4,
      minimumValidWorks: 1,
      relatedSkills: ["expression", "specialty", "collaboration"],
      targetDirections: ["game", "chat", "creative"],
      supportedLanguages: ["jp", "en"],
      requiredWorkTypes: ["PUBLIC_CONTENT", "COLLABORATION", "SPECIALTY"],
    },
    weeklyResourceCapacity: { MANAGER_ASSIST: 18, RECORDING_SLOT: 3, THREE_D_SLOT: 2, PROJECT_COORDINATION: 7, PROMOTION_SLOT: 2 },
  },
});
