export const BALANCE = Object.freeze({
  id: "balance_standard_0_1",
  sourceType: "DESIGN_VALUE",
  note: "规格书 1.0 的初始测试参数，尚未标记为已完成商业平衡。",
  calendar: {
    startDate: "2026-09-14",
    timezone: "Asia/Tokyo",
    slotsPerWeek: 14,
    defaultLifeSlots: 4,
    lockedLifeSlots: 2,
    budgetCycleDays: 28,
    careerReviewWeek: 104,
  },
  initialState: {
    cashFreeJpy: "600000",
    fatigue: 20,
    stress: 20,
    motivation: 60,
    physicalCondition: 90,
    workReputation: 50,
  },
  costs: { weeklyLivingJpy: "15000", weeklyIndieToolsJpy: "3000" },
  contracts: {
    corporatePlatformCreatorShareBps: 6000,
    corporateSponsorCreatorShareBps: 7000,
    corporateMerchProfitRoyaltyBps: 3000,
    corporatePlatformDelayDays: 42,
    defaultTermWeeks: 52,
    defaultNoticeWeeks: 4,
  },
  sponsorship: {
    minimumAverageViews28d: 800,
    minimumWorkReputation: 50,
    baseQuoteJpy: 5000,
    perAverageViewJpy: 6,
    brandFitBonusJpy: 10000,
    quoteCapJpy: 250000,
    personalUpfrontBps: 3000,
    offerValidityDays: 14,
    deliveryDays: 14,
    reviewLeadDays: 7,
    finalPaymentDays: 14,
    offerCooldownWeeks: 4,
  },
  membership: {
    priceJpy: 500,
    cycleDays: 28,
    standardPromiseUnits: 2,
    lightPromiseUnits: 1,
  },
  audition: {
    screeningThreshold: 50,
    finalThreshold: 65,
    slotsPerRound: 2,
    roundIntervalWeeks: 4,
    reapplyCooldownWeeks: 12,
    offerValidityDays: 14,
    offerExtensionDays: 14,
    interviewPrepPerSlot: 2,
    interviewPrepCap: 8,
    finalNoiseMinimum: -3,
    finalNoiseMaximum: 3,
    backgroundCandidatesPerRound: 3,
  },
  merch: {
    acrylicStand: {
      id: "ACRYLIC_STAND_STANDARD",
      name: "亚克力立牌预售",
      productKind: "PHYSICAL",
      salesMode: "PRESALE",
      unitPriceJpy: 2500,
      unitProductionCostJpy: 900,
      storeFeeBps: 800,
      fixedDesignSampleCostJpy: 120000,
      minimumOrderQuantity: 50,
      designWorkUnits: 2,
      samplingDays: 14,
      salesDays: 14,
      productionDays: 28,
      fulfillmentDays: 7,
      afterSalesDays: 14,
      negotiatedUnitCostBps: 13000,
    },
    readyStockBadge: {
      id: "READY_STOCK_BADGE_STANDARD",
      name: "徽章少量现货",
      productKind: "PHYSICAL",
      salesMode: "READY_STOCK",
      unitPriceJpy: 900,
      unitProductionCostJpy: 300,
      storeFeeBps: 800,
      fixedDesignSampleCostJpy: 60000,
      minimumOrderQuantity: 0,
      initialStockQuantity: 50,
      designWorkUnits: 2,
      samplingDays: 7,
      salesDays: 14,
      productionDays: 14,
      fulfillmentDays: 7,
      afterSalesDays: 14,
      negotiatedUnitCostBps: 10000,
    },
    digitalVoicePack: {
      id: "DIGITAL_VOICE_PACK_STANDARD",
      name: "数字语音包",
      productKind: "DIGITAL",
      salesMode: "DIGITAL",
      unitPriceJpy: 1200,
      unitProductionCostJpy: 0,
      storeFeeBps: 800,
      fixedDesignSampleCostJpy: 40000,
      minimumOrderQuantity: 0,
      initialStockQuantity: 0,
      designWorkUnits: 2,
      samplingDays: 0,
      salesDays: 14,
      productionDays: 0,
      fulfillmentDays: 0,
      afterSalesDays: 14,
      negotiatedUnitCostBps: 10000,
    },
  },
  longProjects: {
    newOutfit: {
      id: "NEW_OUTFIT_STANDARD",
      name: "新衣装",
      projectType: "NEW_OUTFIT",
      budgetJpy: 150000,
      workUnits: 4,
      minimumCalendarDays: 28,
      assetType: "OUTFIT",
      resourceRequirements: [
        { resourceType: "DESIGN_SUPPLIER_ORDER", quantity: 1 },
        { resourceType: "MANAGER_ASSIST", quantity: 1, companyOnly: true },
      ],
      effect: { visualProductionBonus: 5, visualProductionBonusCap: 20, revealWindows: 1 },
    },
    coverRecording: {
      id: "COVER_RECORDING_STANDARD",
      name: "翻唱／录音作品",
      projectType: "COVER_RECORDING",
      budgetJpy: 120000,
      workUnits: 5,
      minimumCalendarDays: 21,
      assetType: "MUSIC_RECORDING",
      resourceRequirements: [
        { resourceType: "RECORDING_SLOT", quantity: 2 },
        { resourceType: "USAGE_LICENSE", quantity: 1 },
      ],
      effect: { portfolioKind: "MUSIC", longTail: true },
    },
    originalSong: {
      id: "ORIGINAL_SONG_STANDARD",
      name: "原创曲",
      projectType: "ORIGINAL_SONG",
      budgetJpy: 350000,
      workUnits: 8,
      minimumCalendarDays: 42,
      assetType: "ORIGINAL_MUSIC",
      resourceRequirements: [
        { resourceType: "RECORDING_SLOT", quantity: 3 },
        { resourceType: "SONG_PRODUCTION_SUPPLIER", quantity: 1 },
        { resourceType: "PROJECT_COORDINATION", quantity: 1 },
      ],
      effect: { portfolioKind: "MUSIC", longTail: true },
    },
    anniversary3d: {
      id: "ANNIVERSARY_3D_STANDARD",
      name: "3D 周年企划",
      projectType: "ANNIVERSARY_3D",
      budgetJpy: 600000,
      workUnits: 12,
      minimumCalendarDays: 56,
      assetType: "THREE_D_PRODUCTION",
      resourceRequirements: [
        { resourceType: "THREE_D_SLOT", quantity: 2 },
        { resourceType: "RECORDING_SLOT", quantity: 1 },
        { resourceType: "PROJECT_COORDINATION", quantity: 2 },
      ],
      effect: { portfolioKind: "STAGE", longTail: true },
    },
  },
  audience: {
    totalMarket: 2_000_000,
    backgroundRecommendationWeight: 40,
    baseImpressionPoolPerSegmentSlot: 20_000,
  },
});

export const RULESET_IDS = Object.freeze({
  platform: "platform_youtube_reference_2026_09_12_v1",
  balance: BALANCE.id,
  content: "content_core_1_0",
});
